[[constraint]]
  name = "github.com/bitrise-io/bitrise"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-utils"

[[constraint]]
  name = "github.com/codegangsta/cli"
  branch = "master"

[[constraint]]
  name = "github.com/hashicorp/go-version"
  branch = "master"

[[constraint]]
  name = "github.com/pkg/errors"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  branch = "master"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  branch = "v2"

[prune]
  go-tests = true
  unused-packages = true
