[[constraint]]
  name = "github.com/bitrise-io/bitrise"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-utils"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "v1.21.0"

[[constraint]]
  name = "github.com/hashicorp/go-version"
  version = "v1.2.0"

[[constraint]]
  name = "github.com/pkg/errors"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  branch = "master"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "v2"
  
# https://github.com/gruntwork-io/terratest/issues/368
[[override]]
  name = "github.com/russross/blackfriday"
  version = "1.5.2"

[prune]
  go-tests = true
  unused-packages = true
